// in a standard workflow, this file is automatically generated by expo, but
// it's not always working as expected, so this workaround is needed
// https://github.com/t3-oss/create-t3-turbo/issues/741#issuecomment-1817662268
import 'expo-router/entry';

// avoid adding more code to this file, use relevant routes in /app instead
