/**
 * Courier Redux Fragment
 *
 * Exports action types, action creators, reducers and selectors related to the
 * Courier in the application
 *
 * Currently just courier tasks
 */
import {
  LOAD_TASKS_FAILURE,
  LOAD_TASKS_REQUEST,
  LOAD_TASKS_SUCCESS,
  addPicture,
  addSignature,
  clearTasksFilter,
  deletePictureAt,
  deleteSignatureAt,
  filterTasks,
  loadTasks,
  loadTasksFailure,
  loadTasksRequest,
  loadTasksSuccess,
  markTaskDone,
  markTaskDoneFailure,
  markTaskDoneRequest,
  markTaskDoneSuccess,
  markTaskFailed,
  markTaskFailedFailure,
  markTaskFailedRequest,
  markTaskFailedSuccess,
  markTasksDone,
  markTasksDoneFailure,
  markTasksDoneRequest,
  markTasksDoneSuccess,
  setHideUnassignedFromMap,
  setKeepAwake,
  setPolylineOn,
  setSignatureScreenFirst,
  setTasksChangedAlertSound,
  startTask,
} from './taskActions';
import { tasksEntityReducer } from './taskEntityReducer';
import {
  selectAreDoneTasksHidden,
  selectAreFailedTasksHidden,
  selectFilteredTasks,
  selectIsHideUnassignedFromMap,
  selectIsPolylineOn,
  selectIsTagHidden,
  selectIsTaskCompleteFailure,
  selectIsTasksLoading,
  selectIsTasksLoadingFailure,
  selectKeepAwake,
  selectPictures,
  selectSignatureScreenFirst,
  selectSignatures,
  selectTagNames,
  selectTags,
  selectTaskSelectedDate,
  selectTasks,
  selectTasksChangedAlertSound,
  selectTasksWithColor,
} from './taskSelectors';
import { tasksUiReducer } from './taskUiReducer';

export {
  LOAD_TASKS_FAILURE,
  LOAD_TASKS_REQUEST,
  LOAD_TASKS_SUCCESS,
  addPicture,
  addSignature,
  clearTasksFilter,
  deletePictureAt,
  deleteSignatureAt,
  filterTasks,
  loadTasks,
  loadTasksFailure,
  loadTasksRequest,
  loadTasksSuccess,
  markTaskDone,
  markTaskDoneFailure,
  markTaskDoneRequest,
  markTaskDoneSuccess,
  markTaskFailed,
  markTaskFailedFailure,
  markTaskFailedRequest,
  markTaskFailedSuccess,
  markTasksDone,
  markTasksDoneFailure,
  markTasksDoneRequest,
  markTasksDoneSuccess,
  selectAreDoneTasksHidden,
  selectAreFailedTasksHidden,
  selectFilteredTasks,
  selectIsHideUnassignedFromMap,
  selectIsPolylineOn,
  selectIsTagHidden,
  selectIsTaskCompleteFailure,
  selectIsTasksLoading,
  selectIsTasksLoadingFailure,
  selectKeepAwake,
  selectPictures,
  selectSignatureScreenFirst,
  selectSignatures,
  selectTagNames,
  selectTags,
  selectTaskSelectedDate,
  selectTasks,
  selectTasksChangedAlertSound,
  selectTasksWithColor,
  setHideUnassignedFromMap,
  setKeepAwake,
  setPolylineOn,
  setSignatureScreenFirst,
  setTasksChangedAlertSound,
  startTask,
  tasksEntityReducer,
  tasksUiReducer,
};
