import Home from './Home'

export default {
  RestaurantsPage: require('./RestaurantsPage'),
  RestaurantPage: require('./RestaurantPage'),
  RestaurantList: require('./restaurant/List'),
  RestaurantDashboard: require('./restaurant/Dashboard'),
  RestaurantOrder: require('./restaurant/Order'),
  RestaurantOrderRefuse: require('./restaurant/OrderRefuse'),
  RestaurantOrderDelay: require('./restaurant/OrderDelay'),
  RestaurantOrderCancel: require('./restaurant/OrderCancel'),
  RestaurantDate: require('./restaurant/Date'),
  RestaurantStatus: require('./restaurant/Status'),
  CartPage: require('./CartPage'),
  CartAddressPage: require('./CartAddressPage'),
  CourierPage: require('./CourierPage'),
  CourierTasksPage: require('./courier/TasksPage'),
  CourierTaskListPage: require('./courier/TaskListPage'),
  CourierTaskPage: require('./courier/TaskPage'),
  CourierTaskHistoryPage: require('./courier/TaskHistoryPage'),
  CourierSettingsPage: require('./courier/SettingsPage'),
  AccountPage: require('./AccountPage'),
  AccountAddressesPage: require('./account/AccountAddressesPage'),
  AccountOrdersPage: require('./account/AccountOrdersPage'),
  AccountDetailsPage: require('./account/AccountDetailsPage'),
  CreditCardPage: require('./CreditCardPage'),
  OrderTrackingPage: require('./OrderTrackingPage'),
  Loading: require('./Loading'),
  Home,
  Courier: require('./CourierPage'),
  ConfigureServer: require('./ConfigureServer')
}
