module.exports = {
  HomePage: require('./HomePage'),
  HomeTab: require('./HomeTab'),
  LoginPage: require('./LoginPage'),
  RestaurantsPage: require('./RestaurantsPage'),
  RestaurantPage: require('./RestaurantPage'),
  CartPage: require('./CartPage'),
  CartAddressPage: require('./CartAddressPage'),
  DispatchPage: require('./DispatchPage'),
  AccountPage: require('./AccountPage'),
  AccountAddressesPage: require('./account/AccountAddressesPage'),
  AccountOrdersPage: require('./account/AccountOrdersPage'),
  AccountDetailsPage: require('./account/AccountDetailsPage'),
  CreditCardPage: require('./CreditCardPage'),
  OrderTrackingPage: require('./OrderTrackingPage'),
}