module.exports = {
  HomePage: require('./HomePage'),
  HomeTab: require('./HomeTab'),
  RestaurantsPage: require('./RestaurantsPage'),
  RestaurantPage: require('./RestaurantPage'),
  CartPage: require('./CartPage'),
  CartAddressPage: require('./CartAddressPage'),
  CourierPage: require('./CourierPage'),
  CourierTasksPage: require('./courier/TasksPage'),
  CourierTaskListPage: require('./courier/TaskListPage'),
  CourierTaskPage: require('./courier/TaskPage'),
  CourierTaskHistoryPage: require('./courier/TaskHistoryPage'),
  DispatchPage: require('./DispatchPage'),
  AccountPage: require('./AccountPage'),
  AccountAddressesPage: require('./account/AccountAddressesPage'),
  AccountOrdersPage: require('./account/AccountOrdersPage'),
  AccountDetailsPage: require('./account/AccountDetailsPage'),
  CreditCardPage: require('./CreditCardPage'),
  OrderTrackingPage: require('./OrderTrackingPage'),
}