name: Build CoopCycle APK on release

on:
  release:
    types: [published]

jobs:
  build-coopcycle:
    name: Build CoopCycle APK
    uses: ./.github/workflows/fastlane_android.yml
    with:
      tag: ${{ github.event.release.tag_name }}
      deploy_google_play: false
    secrets: inherit

  upload-apk:
    name: Upload APK to Release
    runs-on: ubuntu-latest
    needs: build-coopcycle
    steps:
      - name: Download CoopCycle APK artifact
        uses: actions/download-artifact@v4
        with:
          name: CoopCycle-release.apk

      - name: List downloaded files (debug)
        run: ls -la

      - name: Upload APK to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          APK_FILE=$(find . -name "*.apk" -type f | head -n 1)

          if [ -z "$APK_FILE" ]; then
            echo "❌ No APK file found!"
            exit 1
          fi

          echo "📦 Uploading $APK_FILE to release"
          gh release upload ${{ github.event.release.tag_name }} "$APK_FILE" --clobber
